Syntax 7

Comment "Reeder S19 Max Pro S"

Include.pcm_split.File "/common/pcm/split.conf"

Macro [
	{
		SplitPCM {
			Name "ums9230_mono_in"
			Direction Capture
			Channels 1
			HWChannels 2
			HWChannelPos0 MONO
			HWChannelPos1 MONO
		}
	}
]

SectionUseCase."HiFi" {
	File "/Unisoc/ums9230/reeder-s19mps/HiFi.conf"
	Comment "Default"
}

SectionUseCase."Voice Call" {
	File "/Unisoc/ums9230/reeder-s19mps/VoiceCall.conf"
	Comment "Voice call"
}

SectionDefaults [
	cset "name='FE_FAST_PLAYBACK TX Switch' off"
	cset "name='FE_CAPTURE_DSP RX Switch' off"
	cset "name='FE_VOICE TX Switch' off"
	cset "name='FE_VOICE RX Switch' off"
]
