SectionVerb {
	EnableSequence [
		cset "name='TX1 SEL' IIS0"
		cset "name='RX2 SEL' IIS1"

		cset "name='Headphone Playback Switch' on"
		cset "name='Headphone Volume' 9"
		cset "name='Swap ADC Channels' on"
		cset "name='ADCL Mixer MIC' on"
		cset "name='Capture Volume' 7"

		cset "name='FE_VOICE TX Switch' on"
		cset "name='FE_VOICE RX Switch' on"
	]

	DisableSequence [
		cset "name='ADCL Mixer MIC' off"
		cset "name='Swap ADC Channels' off"
		cset "name='Headphone Volume' 0"
		cset "name='Headphone Playback Switch' off"
	]

	Value {
		TQ "Voice"
		PlaybackRate 8000
		CaptureRate 8000
	}
}

SectionDevice."Voice Call" {
}
